apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-banana
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: registry.cn-hangzhou.aliyuncs.com/qinyujia-test/busybox
        command: ["sh", "-c", "echo Processing item banana && sleep 5"]
      restartPolicy: Never
      
