apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose:  demostrate-envars
spec:
  containers:
  - name: envar-demo-container
    image:  registry.cn-hangzhou.aliyuncs.com/magina-k8s/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value:  "Hello from the environment"
    - name: DEMO_FAREWELL
      value:  "Such a sweet sorrow"