apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image:  registry.cn-hangzhou.aliyuncs.com/ylck77/liveness:e2e
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value:  Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
