apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-2
spec:
  securityContext:
    runAsUser:  1000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo-2
    image:  registry.cn-hangzhou.aliyuncs.com/magina-k8s/node-hello:1.0
    securityContext:
      runAsUser:  2000
      allowPrivilegeEscalation: false