apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser:  1000
    fsGroup:  2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image:  registry.cn-hangzhou.aliyuncs.com/magina-k8s/node-hello:1.0
    volumeMounts:
    - name: sec-ctx-vol
      mountPath:  /data/demo
    securityContext:
      allowPrivilegeEscalation: false